### ISSUE TITLE
Xyce testing not working

### ISSUE THREAD

**Issue by bmpersc** [trilinos/Trilinos#1129]
@hkthorn reported that the Trilinos Xyce testing is not running correctly and it looks like the issue is the environment is not set right.  @trilinos/framework

**Comment by bmpersc** [comment]
@hkthorn I have fixed the environment issue and the job is running again now. However, it is showing some issues where C++11 values have snuck their way into Teuchos. I will file a ticket against Teuchos for this problem. I'll leave this ticket open until we can verify that the job is still building all the necessary bits for Xyce's needs.

**Comment by bmpersc** [comment]
@hkthorn The ticket for Teuchos is at https://github.com/trilinos/Trilinos/issues/1131. I wasn't sure if you wanted to follow it so I didn't mention you in the ticket.

**Comment by hkthorn** [comment]
Thanks @bmpersc!

**Comment by bartlettroscoe** [comment]
Is this not fixed?  After all, we see:

* http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2785302

Should this issue not be closed now?

@jwillenbring, what do you think?

**Comment by jwillenbring** [comment]
I think @bartlettroscoe is right. There is a separate ticket for the remaining failure for this build and the build is now running properly and reporting, so I am going to close this ticket.
