### ISSUE TITLE
seacas/kokkos: No symbols exported on windows

### ISSUE THREAD

**Issue by Neumann-A** [trilinos/Trilinos#11306]
## Enhancement
@trilinos/seacas @trilinos/kokkos

Passing `BUILD_SHARED_LIBS=ON` to cmake breaks the build of those packages since they are missing required export statements `__declspec(dllexport)` which makes VS not generated an imported library at all which would be required for other parts of the project leading to file acces failures due the missing files.

Either deactivate shared builds on windows or fix the export statements.

**Comment by GrahamBenHarper** [comment]
@trilinos/seacas

@Neumann-A FYI Kokkos is maintained separately at https://github.com/kokkos/kokkos/

**Comment by gsjaardema** [comment]
The required exports have recently been added to the SEACS github repository at https://github.com/sandialabs/seacas.  This will be snapshotted into Trilinos soon which should fix this issue...

**Comment by hartsw** [comment]
I've had decent success building Trilinos with `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON` which is a blunt force way to get a CMake project to export all symbols.  You still need to do some tweaking, but it's not that bad.

Some components still don't work right, but I've gotten most to compile.
