### ISSUE TITLE
SEACAS: header "fmt/ostream.h" not found in Nalu and Albany builds

### ISSUE THREAD

**Issue by spdomin** [trilinos/Trilinos#11487]
## Bug Report
In file included from /ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/include/Ioss_StructuredBlock.h:16,
                 from /ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/include/Ioss_SubSystem.h:35,
                 from /home/spdomin/gitHubWork/nightlyBuildAndTest/NaluNightly/src/InputOutputRealm.C:24:
/ascldap/users/spdomin/gitHubWork/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/include/Ioss_ZoneConnectivity.h:14:10: fatal error: fmt/ostream.h: No such file or directory
   14 | #include <fmt/ostream.h>

Good:
NaluCFD/Nalu SHA1: 8959168ab0f53a39178694457d276d4b887bcf1a
Trilinos/develop SHA1: e9b4687e7a95c0626abd0bc64da33e42470895fe

Bad:
NaluCFD/Nalu SHA1: 8959168ab0f53a39178694457d276d4b887bcf1a
Trilinos/develop SHA1: 7ab1eeca884dbfff6eedfd906f7affa10c773b44

Perhaps @alanw0 could advise.

best,

**Comment by alanw0** [comment]
Hmm, I'm not sure what might be going on here. @gsjaardema could this be caused by recent seacas changes?

**Comment by jhux2** [comment]
Could be related to #11442.

**Comment by jhux2** [comment]
Also affecting Albany.  @ikalash

**Comment by alanw0** [comment]
A quick glance through InputOutputRealm.C seems to indicate that you are not using IOSS directly in that file, you are only using it through stk_io. Thus, you don't need to directly include an IOSS header.
Also glancing at Realm.C, it appears as though you are using Ioss::Property, so you do need to include Ioss_PropertyManager.h, but it doesn't look like Realm.C needs to include Ioss_SubSystem.h either.

**Comment by spdomin** [comment]
Agreed. i will plan on removing the includes and wait to see how this story unfolds.

I seem to recall a tool that can be run to remove extra header includes. I should probably track this down and prune the 10 years of headers that appear via legacy.

**Comment by jhux2** [comment]
> I seem to recall a tool that can be run to remove extra header includes. I should probably track this down and prune the 10 years of headers that appear via legacy.

@spdomin You might be thinking of clang's include-what-you-use (iwyu).

**Comment by jhux2** [comment]
Fyi, manually copying the header `ostream.h` into `INSTALL/include/fmt/ostream.h` reportedly fixes this error in the Albany build on Perlmutter.

@bartlettroscoe git history indicates there were some Tribits changes in SEACAS recently.  Is there a chance that those could have affected header installation?

**Comment by mcarlson801** [comment]
> Fyi, manually copying the header `ostream.h` into `INSTALL/include/fmt/ostream.h` reportedly fixes this error in the Albany build on Perlmutter.

This error is showing up now after manually copying the header. Not sure if it is related to this issue but I figured I'd point it out just in case.
```/usr/bin/ld: ../../../src/libalbanyLib.so: undefined reference to `Albany::getMpiCommFromTeuchosComm(Teuchos::RCP<Teuchos::Comm<int> const>&)'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/unit/evaluators/CMakeFiles/scatterResidual_unit_tester.dir/build.make:227: tests/unit/evaluators/scatterResidual_unit_tester] Error 1
make[1]: *** [CMakeFiles/Makefile2:2125: tests/unit/evaluators/CMakeFiles/scatterResidual_unit_tester.dir/all] Error 2```

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe git history indicates there were some Tribits changes in SEACAS recently. Is there a chance that those could have affected header installation?

I don't thing any changes in TriBITS lately would impact this.  

@gsjaardema, is there a missing install for this file in the SEACAS CMakeLists.txt files?

**Comment by ikalash** [comment]
This may be a separate issue, but it appears the usage of StkMeshIoBroker has changed as well?  Some of the Albany nightlies also have this error:

```
/.../repos/Albany/src/disc/stk/Albany_STKDiscretization.cpp(2333): error: no instance of constructor "stk::io::StkMeshIoBroker::StkMeshIoBroker" matches the argument list
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=44332

**Comment by alanw0** [comment]
Hi @ikalash , the constructor for StkMeshIoBroker hasn't changed recently, still needs a 'stk::ParallelMachine' which is a typedef for MPI_Comm if this is an MPI-enabled build. The build output appears to show that you are giving it an MPI_Comm, assuming that is what is returned by 'getMpiCommFromTeuchosComm'. (Although coincidentally that particular function is reported above by @mcarlson801 to be an undefined reference... Strange.)

**Comment by ikalash** [comment]
Thanks @alanw0 for the comment.  I think I will wait for the seacas issues to be resolved and see if this error remains...

**Comment by gsjaardema** [comment]
The seacas issue was caused by the use of lib{fmt} for output.  This has been used for several years as a header-only library.  In the most recent commit, some of the includes of the fmt files appear in header files that applications using SEACAS are including which means that the lib{fmt} include files must be available to the applications where previously the include files only had to be available during the SEACAS build itself.

I have a commit which removes all lib{fmt} includes from the sEACAS includes which should fix the issue until lib{fmt} becomes a TPL.  I could also install the lib{fmt} include files during a SEACAS build since lib{fmt} is embedded in the SEACAS source, but for now will try the removal route.

**Comment by gsjaardema** [comment]
Is anyone on this issue still having problems, or did #11489 fix the problem(s)

**Comment by bartlettroscoe** [comment]
@spdomin, does this fix the problem with Nalu as well?

**Comment by spdomin** [comment]
Nalu did not formally require these headers. As such, as soon as the error showed up, I removed the extra headers and Nalu was up and building.

**Comment by spdomin** [comment]
This error is back:

Bad: Trilinos/develop SHA1: 94b60d005ec42fe20eda3a869712ffab8548b271
Good: Trilinos/develop SHA1: c8548cf7bdc5a50daff9fdf93d493228a74a3973

In file included from /projects/netpub/nalu/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/include/stk_io/IossBridge.hpp:41,
                 from /fgs/spdomin/nightly/Nalu/src/DataProbePostProcessing.C:33:
/projects/netpub/nalu/scratch_build/install/gcc10.3.0/Trilinos_nightly_release/include/Ioss_Field.h:12:10: fatal error: fmt/ostream.h: No such file or directory
   12 | #include <fmt/ostream.h>

Perhaps this hit Albany as well again? @ikalash

**Comment by spdomin** [comment]
It does not seem like I can re-open this ticket; I will create a new one.

**Comment by ikalash** [comment]
@spdomin : thanks for bringing this to my attention.  I can confirm that we are seeing the issue in Albany again as well, starting today.

**Comment by rppawlo** [comment]
@gsjaardema

**Comment by gsjaardema** [comment]
Sorry for this.  I will try to put a sustainable fix into SEACAS so I don't have to remember to manually change the code on snapshots...

**Comment by spdomin** [comment]
I will report back on Monday. We should have a number of nightly tests by then. In fact, Mac should start soon. 

Thank you.
