### ISSUE TITLE
Trilinos-Xyce testing for C++11=OFF is failing

### ISSUE THREAD

**Issue by hkthorn** [trilinos/Trilinos#1288]
@trilinos/framework @jwillenbring  @bmpersc It looks like the environment issues with the Trilinos-Xyce testing were fixed, but the nightly testing of this build still does not complete.

**Comment by jwillenbring** [comment]
This was running properly as of a few weeks ago:

[http://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-04-17](http://testing.sandia.gov/cdash/index.php?project=Trilinos&date=2017-04-17)

@bmpersc Any thoughts on what changed around this time?

**Comment by bmpersc** [comment]
It looks like it was dying because of a change to tribits to use an option to git that doesn't exist on the default git for RHEL6. I changed the test to use the sems git 2.10.1 which does support the option used. That should fix it for tonight.

I recall that when this first happened that I checked all the tests to make sure that either they were working or if they weren't that the git was updated if it was the problem. It looks like this slipped through the cracks because it is using the master branch which wasn't updated with this change while working through the issues with it. The question I have is should this be pulling from the master branch for its script repo or should I change that to develop?

**Comment by jwillenbring** [comment]
As of the last run there are still errors, but what @bmpersc did fixed the issue that was causing the build to not display on the dashboard. Additionally, I did update the build to pull the script repo from the develop branch as suggested. The build is now reporting, so I think we can close this ticket. (The failures in the build should be tracked separately.)

@hkthorn if you agree we can close this ticket, please do so, let us know what else should be done within the scope of this ticket. If we don't hear from you by Wednesday, we will assume it is OK to close this one.

[http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2883526](http://testing.sandia.gov/cdash/index.php?project=Trilinos&parentid=2883526)

**Comment by bartlettroscoe** [comment]
> It looks like it was dying because of a change to tribits to use an option to git that doesn't exist on the default git for RHEL6. I changed the test to use the sems git 2.10.1 which does support the option used. That should fix it for tonight.

Does Jenkins not send out emails when the ctest -S scripts fail?  Does the ctest -S script not return non-zero when it gets failures like this?  If not, we need to address that.

**Comment by hkthorn** [comment]
@jwillenbring @bmpersc So the build is still failing, but that is because of an issue with Ifpack not an issue with the build environment or test scripts.  I guess it's ok to close it, but there still is the issue of the build failures in Ifpack.

**Comment by jwillenbring** [comment]
> So the build is still failing, but that is because of an issue with Ifpack not an issue with the build environment or test scripts. I guess it's ok to close it, but there still is the issue of the build failures in Ifpack.

@hkthorn OK, then we will close this ticket. The build failure is being tracked in #1145. I commented on that earlier today.
