### ISSUE TITLE
MueLu: Link error with Kokkos (& Tpetra) disabled

### ISSUE THREAD

**Issue by mhoemmen** [trilinos/Trilinos#2340]
```
CMakeFiles/MueLu_UnitTests.dir/TentativePFactory.cpp.o: In function `MueLuTests::TentativePFactory_NoQROption_UnitTest<double, int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const':
.../Trilinos/packages/muelu/test/unit_tests/TentativePFactory.cpp:333: undefined reference to `Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode> > Galeri::Xpetra::CreateMap<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>(Xpetra::UnderlyingLib, std::string const&, Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::ParameterList&)'
CMakeFiles/MueLu_UnitTests.dir/UnsmooshFactory.cpp.o: In function `MueLuTests::UnsmooshFactory_UnsmooshTentativeP_UnitTest<double, int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const':
.../Trilinos/packages/muelu/test/unit_tests/UnsmooshFactory.cpp:91: undefined reference to `Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode> > Galeri::Xpetra::CreateMap<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>(Xpetra::UnderlyingLib, std::string const&, Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::ParameterList&)'
CMakeFiles/MueLu_UnitTests.dir/VariableDofLaplacianFactory.cpp.o: In function `MueLuTests::VariableDofLaplacianFactory_VarLaplConstructor2_UnitTest<double, int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const':
.../Trilinos/packages/muelu/test/unit_tests/VariableDofLaplacianFactory.cpp:137: undefined reference to `Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode> > Galeri::Xpetra::CreateMap<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>(Xpetra::UnderlyingLib, std::string const&, Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::ParameterList&)'
CMakeFiles/MueLu_UnitTests.dir/VariableDofLaplacianFactory.cpp.o: In function `MueLuTests::VariableDofLaplacianFactory_VarLaplPtent_UnitTest<double, int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const':
.../Trilinos/packages/muelu/test/unit_tests/VariableDofLaplacianFactory.cpp:235: undefined reference to `Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode> > Galeri::Xpetra::CreateMap<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>(Xpetra::UnderlyingLib, std::string const&, Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::ParameterList&)'
CMakeFiles/MueLu_UnitTests.dir/Repartition.cpp.o: In function 
`MueLuTests::Repartition_CoordinateMap_UnitTest<double, int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const':
.../Trilinos/packages/muelu/test/unit_tests/Repartition.cpp:855: undefined reference to `Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode> > Galeri::Xpetra::CreateMap<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>(Xpetra::UnderlyingLib, std::string const&, Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::ParameterList&)'
collect2: error: ld returned 1 exit status
make[2]: *** [packages/muelu/test/unit_tests/MueLu_UnitTests.exe] Error 1
make[1]: *** [packages/muelu/test/unit_tests/CMakeFiles/MueLu_UnitTests.dir/all] Error 2
make: *** [all] Error 2
```

@trilinos/muelu

**Comment by jhux2** [comment]
@mhoemmen Checkin script is running on a patch that fixes the issue locally for me.

**Comment by mhoemmen** [comment]
Thanks @jhux2 !  I'll try it out, and if it works, I'll close the issue.

**Comment by mhoemmen** [comment]
@jhux2 Hm, it still doesn't work for me.  Do you have OpenMP enabled?
```
[ 95%] Linking CXX executable MueLu_UnitTests.exe

CMakeFiles/MueLu_UnitTests.dir/TentativePFactory.cpp.o: In function `MueLuTests::TentativePFactory_NoQROption_UnitTest<double, int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const':
.../Trilinos/packages/muelu/test/unit_tests/TentativePFactory.cpp:333: undefined reference to `Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode> > Galeri::Xpetra::CreateMap<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>(Xpetra::UnderlyingLib, std::string const&, Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::ParameterList&)'
CMakeFiles/MueLu_UnitTests.dir/UnsmooshFactory.cpp.o: In function `MueLuTests::UnsmooshFactory_UnsmooshTentativeP_UnitTest<double, int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const':
.../Trilinos/packages/muelu/test/unit_tests/UnsmooshFactory.cpp:91: undefined reference to `Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode> > Galeri::Xpetra::CreateMap<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>(Xpetra::UnderlyingLib, std::string const&, Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::ParameterList&)'
CMakeFiles/MueLu_UnitTests.dir/VariableDofLaplacianFactory.cpp.o: In function `MueLuTests::VariableDofLaplacianFactory_VarLaplConstructor2_UnitTest<double, int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const':
.../Trilinos/packages/muelu/test/unit_tests/VariableDofLaplacianFactory.cpp:137: undefined reference to `Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode> > Galeri::Xpetra::CreateMap<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>(Xpetra::UnderlyingLib, std::string const&, Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::ParameterList&)'
CMakeFiles/MueLu_UnitTests.dir/VariableDofLaplacianFactory.cpp.o: In function `MueLuTests::VariableDofLaplacianFactory_VarLaplPtent_UnitTest<double, int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const':
.../Trilinos/packages/muelu/test/unit_tests/VariableDofLaplacianFactory.cpp:235: undefined reference to `Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode> > Galeri::Xpetra::CreateMap<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>(Xpetra::UnderlyingLib, std::string const&, Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::ParameterList&)'
CMakeFiles/MueLu_UnitTests.dir/Repartition.cpp.o: In function `MueLuTests::Repartition_CoordinateMap_UnitTest<double, int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const':
.../Trilinos/packages/muelu/test/unit_tests/Repartition.cpp:855: undefined reference to `Teuchos::RCP<Xpetra::Map<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode> > Galeri::Xpetra::CreateMap<int, int, Kokkos::Compat::KokkosOpenMPWrapperNode>(Xpetra::UnderlyingLib, std::string const&, Teuchos::RCP<Teuchos::Comm<int> const> const&, Teuchos::ParameterList&)'
collect2: error: ld returned 1 exit status
```

**Comment by jhux2** [comment]
@mhoemmen Probably not, I'll check that now.

**Comment by jhux2** [comment]
@mhoemmen What's the reason for building MueLu with Epetra support only and OpenMP enabled?

**Comment by mhoemmen** [comment]
@jhux2 

1. Teuchos has Kokkos profiling hooks for Teuchos::TimeMonitor, but they were disabled by default.  I wanted to make sure that enabling them by default wouldn't break the build. 

2. MueLu declares Tpetra as an optional dependency.  If MueLu requires Tpetra, MueLu should declare Tpetra as a required dependency.

**Comment by mhoemmen** [comment]
FYI I see these on the Dashboard too, in the Specialized track.  The names of the builds may be indicative of the cause:
```
Linux-GCC-5.3.0-OPENMPI_1.10.1_RELEASE_DEV_MueLu_NO_INT_NO_SERIAL_OPENMP
Linux-gcc-5.3.0-OPENMPI-1.10.1_RELEASE_NO-INT_OPENMP_EXPERIMENTAL
Linux-gcc-5.3.0-OPENMPI-1.10.1_RELEASE_NO-INT_NO-SERIAL_OPENMP_EXPERIMENTAL
```

**Comment by jhux2** [comment]
@mhoemmen I have a partial fix, but there is one combination I don't have working yet.  Sorry if this is preventing a push.

> MueLu declares Tpetra as an optional dependency. If MueLu requires Tpetra, MueLu should declare Tpetra as a required dependency.

Epetra and Tpetra are optional dependencies to MueLu, but at least one of them is required.

**Comment by mhoemmen** [comment]
@jhux2 wrote:
> Epetra and Tpetra are optional dependencies to MueLu, but at least one of them is required.

I was exercising the use case in which Epetra was enabled, and Tpetra was disabled.

**Comment by jhux2** [comment]
I just pushed another patch.  Let's see how the dashboard does overnight.

**Comment by mhoemmen** [comment]
Thanks @jhux2 !

**Comment by jhux2** [comment]
Sadly, the tests are still failing.

**Comment by mhoemmen** [comment]
@jhux2 Does that mean they still fail to link, or do they actually link now?

**Comment by jhux2** [comment]
Failure to link.

**Comment by jhux2** [comment]
Sorry for the delay.  I pushed another fix last night that cleared the dashboard failures exhibiting the same errors as in this [comment](https://github.com/trilinos/Trilinos/issues/2340#issue-302417294).  I'll close this issue, but if problems persist, please reopen.
