### ISSUE TITLE
Xpetra/Epetra Undefined Reference when Compiling MueLu Test

### ISSUE THREAD

**Issue by nmhamster** [trilinos/Trilinos#3041]
@trilinos/muelu @trilinos/xpetra 

Compiling Trilinos (with tests) for KNL on Argonne Theta. I am using the Master branch.

Using:
*  Cray MPI
*  Intel 18.2 Compiler
*  OpenMP enabled

```
[100%] Built target MueLu_Viz
[100%] Built target MueLu_Convergence
[100%] Linking CXX executable MueLu_Driver.exe
Warning:
 Headers and libraries from cray-libsci/18.04.1 will be ignored because they conflict with -mkl.

../../../kokkos/core/src/libkokkoscore.a(Kokkos_Profiling_Interface.cpp.o): In function `Kokkos::Profiling::initialize()':

../../../kokkos/core/src/libkokkoscore.a(Kokkos_Profiling_Interface.cpp.o): In function `Kokkos::Profiling::initialize()':
Kokkos_Profiling_Interface.cpp:(.text+0x5c5): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
CMakeFiles/MueLu_Driver.dir/Driver.cpp.o: In function `int main_<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Teuchos::CommandLineProcessor&, Xpetra::UnderlyingLib&, int, char**)':
Driver.cpp:(.text._Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6SerialENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc[_Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6SerialENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc]+0x31ca): undefined reference to `Epetra_MultiVector& Xpetra::toEpetra<long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Xpetra::MultiVector<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&)'
Driver.cpp:(.text._Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6SerialENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc[_Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6SerialENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc]+0x3213): undefined reference to `Epetra_MultiVector& Xpetra::toEpetra<long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Xpetra::MultiVector<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&)'
CMakeFiles/MueLu_Driver.dir/Driver.cpp.o: In function `int main_<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >(Teuchos::CommandLineProcessor&, Xpetra::UnderlyingLib&, int, char**)':
Driver.cpp:(.text._Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6OpenMPENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc[_Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6OpenMPENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc]+0x31ca): undefined reference to `Epetra_MultiVector& Xpetra::toEpetra<long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >(Xpetra::MultiVector<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >&)'
Driver.cpp:(.text._Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6OpenMPENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc[_Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6OpenMPENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc]+0x3213): undefined reference to `Epetra_MultiVector& Xpetra::toEpetra<long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >(Xpetra::MultiVector<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP, Kokkos::HostSpace> >&)'
```

**Comment by jhux2** [comment]
@nmhamster Can you please provide your cmake configure line?

**Comment by cgcgcg** [comment]
@jhux2 See here: https://testing.sandia.gov/cdash/viewBuildError.php?buildid=3664921

**Comment by jhux2** [comment]
I've just hit the error report here while working on #3035.  I'll work on the other issue first, then come back to this one.

**Comment by jhux2** [comment]
Well, darn.  The link error no longer happens for me.

**Comment by lucbv** [comment]
I think this should be resolved by now as this error does not happen anymore on the dashboard. @nmhamster can you check if this works for you now?

**Comment by jhux2** [comment]
@lucbv I don't recall seeing this on the dashboard before (but my memory is terrible).

**Comment by sjohnson-imi** [comment]
I just got this message. (Mac OSX 10.14.2 Mojave) using the master. Is there something specific I should be looking for to fix this?

cmake \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=ON \
-D HAVE_GCC_ABI_DEMANGLE:BOOL=ON \
-D CMAKE_INSTALL_PREFIX=build \
-D Trilinos_ENABLE_TESTS:BOOL=ON \
-D TPL_ENABLE_Matio=OFF \
-D TPL_ENABLE_MPI:BOOL=ON \
-D TPL_ENABLE_HDF5:BOOL=ON \
-D HDF5_INCLUDE_DIRS:PATH=/opt/local/include \
-D HDF5_LIBRARY_DIRS:PATH=/opt/local/lib \
-D MPI_BASE_DIR=/opt/local \
Trilinos-master

**Comment by MarDiehl** [comment]
I have the same issue on Arch Linux with the current release version (12.14.1):

` Driver.cpp:(.text._Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6SerialENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc[_Z5main_IdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6SerialENS0_9HostSpaceEEEEiRN7Teuchos20CommandLineProcessorERN6Xpetra13UnderlyingLibEiPPc]+0x4459): undefined reference to 'Epetra_MultiVector& Xpetra::toEpetra<long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Xpetra::MultiVector<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&)'`

my cmake command is very similar

```
     cmake .. -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \                                      
              -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=ON \                                               
              -DTrilinos_ENABLE_Gtest:BOOL=ON \                                                      
              -DTrilinos_ENABLE_TESTS=ON \                                                           
              -DTPL_ENABLE_gtest:BOOL=ON \                                                           
              -DTPL_ENABLE_MPI:BOOL=ON \                                                             
              -DTPL_ENABLE_HDF5:BOOL=ON \                                                            
              -DPYTHON_EXECUTABLE:PATH=/usr/bin/python2 \                                            
              -DCMAKE_INSTALL_PREFIX:PATH=/usr \                                                     
              -DBUILD_SHARED_LIBS:BOOL=ON
```

Since

**Comment by lucbv** [comment]
@jhux2 do we know if anyone is still encountering this issue?
If not we should close this issue.

**Comment by MarDiehl** [comment]
Is there a new version out? Otherwise, I would assume that the issue is not resolved. Arch linux has always almost the newest compilers, so the issue might pop up in future with other OS as well

**Comment by amklinv** [comment]
I am encountering this issue with 12.16.

**Comment by markyoder** [comment]
I'm seeing it compiling Trilinos v12.18.1 on CentOS-7 HPC system:

```
Simple.cpp:(.text._Z11SystemSolveIdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6SerialENS0_9HostSpaceEEEEvRN7Teuchos3RCPIN6Xpetra6MatrixIT_T0_T1_T2_EEEERNS7_INS8_11MultiVectorISA_SB_SC_SD_EEEESK_RNS7_IN5MueLu9HierarchyISA_SB_SC_SD_EEEERNS7_INS8_8OperatorISA_SB_SC_SD_EEEERNS6_18basic_FancyOStreamIcSt11char_traitsIcEEENSt7__cxx1112basic_stringIcSW_SaIcEEES12_bbbiibbid[_Z11SystemSolveIdilN6Kokkos6Compat23KokkosDeviceWrapperNodeINS0_6SerialENS0_9HostSpaceEEEEvRN7Teuchos3RCPIN6Xpetra6MatrixIT_T0_T1_T2_EEEERNS7_INS8_11MultiVectorISA_SB_SC_SD_EEEESK_RNS7_IN5MueLu9HierarchyISA_SB_SC_SD_EEEERNS7_INS8_8OperatorISA_SB_SC_SD_EEEERNS6_18basic_FancyOStreamIcSt11char_traitsIcEEENSt7__cxx1112basic_stringIcSW_SaIcEEES12_bbbiibbid]+0x3b2): undefined reference to `Epetra_MultiVector& Xpetra::toEpetra<long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >(Xpetra::MultiVector<double, int, long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >&)
```

My CMake ends up being pretty complicated, since I have to name the exact location of just about every component, 'lest the configuration find a random, wrong version of various packages, but the components being used are:
```
CMAKE_FLAGS="${CMAKE_FLAGS} \
-DTrilinos_ENABLE_Amesos=ON                      \
-DTrilinos_ENABLE_Epetra=ON                      \
-DTrilinos_ENABLE_EpetraExt=ON                   \
-DTrilinos_ENABLE_Ifpack=ON                      \
-DTrilinos_ENABLE_AztecOO=ON                     \
-DTrilinos_ENABLE_Sacado=ON                      \
-DTrilinos_ENABLE_Teuchos=ON                     \
-DTrilinos_ENABLE_MueLu=ON                       \
-DTrilinos_ENABLE_ML=ON                          \
-DTrilinos_ENABLE_ROL=ON                         \
-DTrilinos_ENABLE_ROL=ON                         \
-DTrilinos_ENABLE_MUMPS=ON                       \
-DTpetra_INST_COMPLEX_DOUBLE=ON                  \
-DTpetra_INST_COMPLEX_FLOAT=ON                   \
-DTrilinos_ENABLE_Zoltan=ON "
#
# and to satisfy some conflicts:
CMAKE_FLAGS="${CMAKE_FLAGS} \
-DTeuchos_ENABLE_COMPLEX:BOOL=ON            \
-DTrilinos_ENABLE_COMPLEX_DOUBLE=ON "
#
# -DTrilinos_ENABLE_Tpetra=ON                      \
# throw these in for good measure:
CMAKE_FLAGS="${CMAKE_FLAGS} -DSEACASAprepro_lib_ENABLE_SEACASExodus=ON -DTrilinos_ENABLE_SEACASAprepro_lib=ON -DTrilinos_ENABLE_SEACASExodus=ON "
#
```

**Comment by lucbv** [comment]
Could you send us the output from the CMake configuration line?

**Comment by markyoder** [comment]
Here's the output up to `make`. there is a bit of my own preamble, and I
confess that some of this is a bit of a mess, as I am in many cases
guessing at how to format flags, what paths need to be rigorously
specified, etc.

**** BEGIN CMAKE OUTPUT *****

* Compiling with 24

*** MPI_DIR: /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4

*** NetCDF: /opt/ohpc/pub/libs/gnu8/openmpi3/netcdf/4.7.1,
/opt/ohpc/pub/libs/gnu8/openmpi3/netcdf/4.7.1/include,
/opt/ohpc/pub/libs/gnu8/openmpi3/netcdf/4.7.1/lib

***

***

Some MPI vars: /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4,
/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicc,
/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicxx,
/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpifort

***

***

Source exists: /scratch/myoder96/Downloads/trilinos/Trilinos

*** CMAKE_FLAGS:
-DMPI_C_COMPILER=/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicc
-DMPI_CXX_COMPILER=/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicxx
-DMPI_FORTRAN_COMPILER=/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpifort
 -DCMAKE_C_COMPILER=/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicc
-DCMAKE_CXX_COMPILER=/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicxx
-DCMAKE_FORTRAN_COMPILER=/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpifort
 -DTPL_ENABLE_MPI=ON
-DMPI_BASE_DIR=/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4
-DMPI_BIN_DIR=/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin -D
CMAKE_VERBOSE_MAKEFILE=ON -D Trilinos_ENABLE_OpenMP:BOOL=ON  -D
CMAKE_CXX_FLAGS:STRING=-Wall --pedantic  -DBUILD_SHARED_LIBS=ON
-DTrilinos_ENABLE_FLOAT=ON -DTrilinos_ENABLE_TESTS=ON -D
HAVE_GCC_ABI_DEMANGLE=ON
-DTPL_Boost_INCLUDE_DIRS=;/opt/ohpc/pub/libs/gnu8/openmpi3/boost/1.71.0/include
-DTPL_Boost_ROOT_DIR=/opt/ohpc/pub/libs/gnu8/openmpi3/boost/1.71.0;
-DTPL_BoostLib_LIBRARY_DIRS=;/opt/ohpc/pub/libs/gnu8/openmpi3/boost/1.71.0/lib
-DNetcdf_LIBRARY_NAMES=netcdf;netcdf_c++4
-DTPL_Netcdf_INCLUDE_DIRS=/opt/ohpc/pub/libs/gnu8/openmpi3/netcdf/4.7.1/include;/opt/ohpc/pub/libs/gnu8/openmpi3/netcdf/4.7.1/lib;/opt/ohpc/pub/libs/gnu8/openmpi3/netcdf-cxx/4.3.1/include;/opt/ohpc/pub/libs/gnu8/openmpi3/netcdf-cxx/4.3.1/lib;/opt/ohpc/pub/libs/gnu8/openmpi3/netcdf-fortran/4.5.2/include;/opt/ohpc/pub/libs/gnu8/openmpi3/netcdf-fortran/4.5.2/lib
-DTPL_Netcdf_LIBRARIES=/opt/ohpc/pub/libs/gnu8/openmpi3/netcdf/4.7.1/lib/libnetcdf.so;/opt/ohpc/pub/libs/gnu8/openmpi3/netcdf-cxx/4.3.1/lib/libnetcdf_c++4.so
  -DTrilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES=ON
-DTrilinos_ENABLE_ALL_PACKAGES=OFF  -DTrilinos_ENABLE_Amesos=ON
          -DTrilinos_ENABLE_Epetra=ON
-DTrilinos_ENABLE_EpetraExt=ON
                  -DTrilinos_ENABLE_Ifpack=ON
-DTrilinos_ENABLE_AztecOO=ON
                    -DTrilinos_ENABLE_Sacado=ON
-DTrilinos_ENABLE_Teuchos=ON
                    -DTrilinos_ENABLE_Tpetra=ON
-DTrilinos_ENABLE_Xpetra=ON                      -DTrilinos_ENABLE_ML=ON
                      -DTrilinos_ENABLE_ROL=ON
-DTrilinos_ENABLE_ROL=ON
                        -DTrilinos_ENABLE_MUMPS=ON
-DTpetra_INST_COMPLEX_DOUBLE=ON                  -DTpetra_INST_COMPLEX_FLOAT=ON
                  -DTrilinos_ENABLE_MueLu=ON
-DTrilinos_ENABLE_Zoltan=ON  -DTeuchos_ENABLE_COMPLEX:BOOL=ON
  -DTrilinos_ENABLE_COMPLEX_DOUBLE=ON
        -D MueLu_ENABLE_Epetra:BOOL=ON
-DTrilinos_ENABLE_COMPLEX=ON
  -DSEACASAprepro_lib_ENABLE_SEACASExodus=ON
-DTrilinos_ENABLE_SEACASAprepro_lib=ON -DTrilinos_ENABLE_SEACASExodus=ON

*** src: /scratch/myoder96/Downloads/trilinos/Trilinos

-- Found PythonInterp: /usr/local/anaconda3/bin/python (found suitable
version "3.6.8", minimum required is "2.6")

-- Found Git: /share/cees/software/git_2_25/libexec/git-core/git (found
version "2.25.0")

-- Setting Trilinos_ENABLE_EXAMPLES=ON because Trilinos_ENABLE_TESTS=ON

-- Setting CMAKE_BUILD_TYPE=RELEASE since it was not set ...

-- Leaving current
CMAKE_C_COMPILER=/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicc since it
is already set!

-- Leaving current
CMAKE_CXX_COMPILER=/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicxx since
it is already set!

-- Setting CMAKE_Fortran_COMPILER=${MPI_Fortran_COMPILER}

-- The C compiler identification is GNU 8.3.0

-- Check for working C compiler:
/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicc

-- Check for working C compiler:
/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicc -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- The CXX compiler identification is GNU 8.3.0

-- Check for working CXX compiler:
/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicxx

-- Check for working CXX compiler:
/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpicxx -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- The Fortran compiler identification is GNU 8.3.0

-- Check for working Fortran compiler:
/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpif90

-- Check for working Fortran compiler:
/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpif90  -- works

-- Detecting Fortran compiler ABI info

-- Detecting Fortran compiler ABI info - done

-- Checking whether /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpif90
supports Fortran 90

-- Checking whether /opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/bin/mpif90
supports Fortran 90 -- yes

-- Using the legacy tribits build because KOKKOS_ARCH not set

-- 

-- ****************** Kokkos Settings ******************

-- Execution Spaces

--   Device Parallel: None

--     Host Parallel: OpenMP

--       Host Serial: Serial

-- 

-- Architectures:

--     None

-- 

-- Enabled options

--   KOKKOS_ENABLE_SERIAL

--   KOKKOS_ENABLE_OPENMP

--   KOKKOS_ENABLE_PROFILING

--   KOKKOS_ENABLE_DEPRECATED_CODE

-- 

-- Final kokkos settings variable:

--
env;KOKKOS_CMAKE=yes;KOKKOS_SRC_PATH=/scratch/myoder96/Downloads/trilinos/Trilinos/packages/kokkos;KOKKOS_PATH=/scratch/myoder96/Downloads/trilinos/Trilinos/packages/kokkos;KOKKOS_INSTALL_PATH=/share/cees/software/trilinos/gnu8_openmpi3/12.18.1;KOKKOS_ARCH=None;KOKKOS_DEVICES=OpenMP,Serial;KOKKOS_DEBUG=no;KOKKOS_OPTIONS=disable_dualview_modify_check

-- *****************************************************

-- 

-- Looking for C++ include sys/time.h

-- Looking for C++ include sys/time.h - found

-- Looking for C++ include time.h

-- Looking for C++ include time.h - found

-- Looking for C++ include stdint.h

-- Looking for C++ include stdint.h - found

-- Looking for C++ include inttypes.h

-- Looking for C++ include inttypes.h - found

-- Found Perl: /usr/bin/perl (found version "5.16.3")

-- Fortran name mangling: LOWER UNDER

-- Detecting Fortran/C Interface

-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling

-- Verifying Fortran/CXX Compiler Compatibility

-- Verifying Fortran/CXX Compiler Compatibility - Success

-- Performing Test CXX11_FLAGS_COMPILE_RESULT_0

-- Performing Test CXX11_FLAGS_COMPILE_RESULT_0 - Success

-- Performing Test CXX11_CONSECUTIVE_RIGHT_ANGLE_BRACKETS

-- Performing Test CXX11_CONSECUTIVE_RIGHT_ANGLE_BRACKETS - Success

-- Performing Test CXX11_AUTOTYPEDVARIABLES

-- Performing Test CXX11_AUTOTYPEDVARIABLES - Success

-- Performing Test CXX11_LAMBDAS

-- Performing Test CXX11_LAMBDAS - Success

-- Found OpenMP_C: -fopenmp (found version "4.5")

-- Found OpenMP_CXX: -fopenmp (found version "4.5")

-- Found OpenMP_Fortran: -fopenmp (found version "4.5")

-- Found OpenMP: TRUE (found version "4.5")

-- Performing Test MATH_LIBRARY_IS_SUPPLIED

-- Performing Test MATH_LIBRARY_IS_SUPPLIED - Success

-- Performing Test FINITE_VALUE_HAVE_GLOBAL_ISNAN

-- Performing Test FINITE_VALUE_HAVE_GLOBAL_ISNAN - Success

-- Performing Test FINITE_VALUE_HAVE_STD_ISNAN

-- Performing Test FINITE_VALUE_HAVE_STD_ISNAN - Success

-- Performing Test FINITE_VALUE_HAVE_GLOBAL_ISINF

-- Performing Test FINITE_VALUE_HAVE_GLOBAL_ISINF - Success

-- Performing Test FINITE_VALUE_HAVE_STD_ISINF

-- Performing Test FINITE_VALUE_HAVE_STD_ISINF - Success

-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found
components: doxygen dot

-- You set HAVE_GCC_ABI_DEMANGLE=ON; this suggests you are cross compiling.
If you're not cross compiling, best practice is not to set this; Trilinos
will figure it out for you.

-- Performing Test HAVE_TEUCHOSCORE_BOOST_IS_POLYMORPHIC

-- Performing Test HAVE_TEUCHOSCORE_BOOST_IS_POLYMORPHIC - Success

-- Performing Test HAVE_TEUCHOS_BLASFLOAT

-- Performing Test HAVE_TEUCHOS_BLASFLOAT - Success

-- Performing Test LAPACK_SLAPY2_WORKS

-- Performing Test LAPACK_SLAPY2_WORKS - Success

-- Performing Test HAVE_TEUCHOS_LAPACKLARND

-- Performing Test HAVE_TEUCHOS_LAPACKLARND - Failed

-- Performing Test HAVE_CXX_ATTRIBUTE_CONSTRUCTOR

-- Performing Test HAVE_CXX_ATTRIBUTE_CONSTRUCTOR - Success

-- C++ compiler supports __attribute__((constructor)) syntax

-- Performing Test HAVE_CXX_ATTRIBUTE_WEAK

-- Performing Test HAVE_CXX_ATTRIBUTE_WEAK - Success

-- C++ compiler supports __attribute__((weak)) syntax and testing weak
functions

-- Performing Test HAVE_CXX_PRAGMA_WEAK

-- Performing Test HAVE_CXX_PRAGMA_WEAK - Failed

-- C++ compiler does NOT support #pragma weak syntax and testing weak
functions

-- Performing Test CXX_COMPLEX_BLAS_WORKS

-- Performing Test CXX_COMPLEX_BLAS_WORKS - Success

-- Wrapping every Teuchos timer with a Kokkos profiling region.

-- Performing Test KOKKOSKERNELS_TPL_BLAS_RETURN_COMPLEX

-- Performing Test KOKKOSKERNELS_TPL_BLAS_RETURN_COMPLEX - Success

-- Performing Test HAS_C99_TR1_CMATH

-- Performing Test HAS_C99_TR1_CMATH - Success

-- Looking for dggsvd3

-- Looking for dggsvd3 - not found

-- Looking for dggsvd3_

-- Looking for dggsvd3_ - not found

-- Looking for DGGSVD3

-- Looking for DGGSVD3 - not found

-- Looking for DGGSVD3_

-- Looking for DGGSVD3_ - not found

-- Tpetra: Enabling deprecated code

-- Determine whether Tpetra will assume that MPI is CUDA aware:

--   - Tpetra_ENABLE_CUDA is OFF, so Tpetra will assume that MPI is not
CUDA aware.

-- NOTE: Kokkos::Serial is ON (the CMake option Kokkos_ENABLE_Serial is
ON), but the corresponding Tpetra Node type is disabled.  If you want to
enable instantiation and use of Kokkos::Serial in Tpetra, please also set
the CMake option Tpetra_INST_SERIAL:BOOL=ON.  If you use the Kokkos::Serial
Node type in Tpetra without doing this, you will get link errors!

-- Tpetra execution space availability (ON means available):

--   - Serial:  OFF

--   - Threads: OFF

--   - OpenMP:  ON

--   - Cuda:    OFF

-- Tpetra: Tpetra_INST_INT_LONG_LONG is enabled by default.

-- Tpetra: Tpetra_INST_INT_UNSIGNED is disabled by default.

-- Tpetra: Tpetra_INST_INT_UNSIGNED_LONG is disabled by default.

-- Tpetra: Tpetra_INST_INT_INT is enabled by default.

-- Tpetra: Tpetra_INST_INT_LONG is disabled.

-- 

-- Tpetra: Validate global ordinal setting ...

-- 

-- Setting default Node to Kokkos::Compat::KokkosOpenMPWrapperNode.

-- Xpetra: Enabling deprecated code

-- Xpetra: Disabling ETI

-- A Python-2 version of Exodus.py will be installed.

-- MueLu: Enabling deprecated code

-- MueLu: Kokkos_Refactor ON by default

-- Ifpack2: Processing ETI / test support

-- Enabled Scalar types:
float|double|std::complex<float>|std::complex<double>

-- Enabled LocalOrdinal types:  int

-- Enabled GlobalOrdinal types: int|long long

-- Enabled Node types:          Kokkos::Compat::KokkosOpenMPWrapperNode

-- Set of enabled types, before exclusions: S={float}
N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={int};S={float}
N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long
long};S={double} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int}
GO={int};S={double} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int}
GO={long long};S={std::complex<float>}
N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int}
GO={int};S={std::complex<float>}
N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long
long};S={std::complex<double>} N={Kokkos::Compat::KokkosOpenMPWrapperNode}
LO={int} GO={int};S={std::complex<double>}
N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long long}

-- TpetraCore: Processing ETI / test support

-- Enabled Scalar types:        int|long
long|float|double|std::complex<float>|std::complex<double>

-- Enabled LocalOrdinal types:  int

-- Enabled GlobalOrdinal types: int|long long

-- Enabled Node types:          Kokkos::Compat::KokkosOpenMPWrapperNode

-- Set of enabled types, before exclusions: S={int} LO={int} GO={int}
N={Kokkos::Compat::KokkosOpenMPWrapperNode};S={int} LO={int} GO={long long}
N={Kokkos::Compat::KokkosOpenMPWrapperNode};S={int}
N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={int};S={int}
N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long long};S={long
long} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={int};S={long
long} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long
long};S={float} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int}
GO={int};S={float} N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int}
GO={long long};S={double} N={Kokkos::Compat::KokkosOpenMPWrapperNode}
LO={int} GO={int};S={double} N={Kokkos::Compat::KokkosOpenMPWrapperNode}
LO={int} GO={long long};S={std::complex<float>}
N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int}
GO={int};S={std::complex<float>}
N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long
long};S={std::complex<double>} N={Kokkos::Compat::KokkosOpenMPWrapperNode}
LO={int} GO={int};S={std::complex<double>}
N={Kokkos::Compat::KokkosOpenMPWrapperNode} LO={int} GO={long long}

-- Configuring done

-- Generating done

-- Build files have been written to:
/scratch/myoder96/Downloads/trilinos/Trilinos/build_gnu8_openmpi3

*** CMAKE done. do make!

**** END CMAKE OUTPUT ****


Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"If you bore me, you lose your soul (to me)..."
~belly

**Comment by lucbv** [comment]
Yeah that looks a bit strange to me, at least I am not used to this type of output. Maybe I can also ask you what you are trying to do with Trilinos and I could give you a corresponding working configuration?

**Comment by markyoder** [comment]
Honestly, I'm just trying to compile it for a graduate student, principally
as a required component for Deal.II. We have v12.14 pre-compiled as an
OpenHPC component, which I'd love to use, but it throws an error --
something about "OpenMP enabled for {some component} but not enabled on
compiler!", which appears (from what I've found so far) to be an in-code
bug, so I'm trying to compile a newer release.

as for the output: there is a bit of front-matter, but everything after:
" Source exists: /scratch/myoder96/Downloads/trilinos/Trilinos "

is pure CMAKE output.

It looks like i accidentally include a 'demangling' option. I'm going to
pull that, and have a closer look at some other options as well to see how
that goes.

Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"If you bore me, you lose your soul (to me)..."
~belly

**Comment by brian-kelley** [comment]
@markyoder I was able to replicate the error. The easiest fix is to add
```
-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON
```
to CMake flags. This will also speed up the build significantly. The build you had is supposed to work in theory, so next I'm going to see if the master-branch version has fixed it since 12.18.1 (a lot of build related stuff has changed since then).

**Comment by markyoder** [comment]
Ok. I'll see about working from the master branch as well. Thanks!

mark

Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"If you bore me, you lose your soul (to me)..."
~belly

**Comment by cgcgcg** [comment]
@markyoder Could you try the develop branch instead? I merged a commit that might fix the issue.

**Comment by brian-kelley** [comment]
After adding this one-line change in #7237, a similar build of develop branch succeeded. However, unlike v12.18.1, only one global ordinal type can be enabled (so choose either ``-DTpetra_INST_INT_LONG_LONG`` (the default) or ``-DTpetra_INST_INT_INT``, but not both).

**Comment by markyoder** [comment]
Ok, almost there I think. I am also seeing errors like this in more than one place:
```
/scratch/myoder96/Downloads/trilinos/Trilinos/packages/muelu/src/Graph/MatrixTransformation/MueLu_CoalesceDropFactory_kokkos_def.hpp:524:35: error: no match for ‘operator==’ (operand types are ‘double’ and ‘const SC’ {aka ‘const std::complex<float>’})
     if (blkSize == 1 && threshold == zero) {
```
If you trace this back, it's usually what it sounds like, an operator like `--` or `*` not supported for a `complex<>` type. Are these related to setting the CMAKE flags, `-DTrilinos_ENABLE_COMPLEX=ON`, and/or `-DTrilinos_ENABLE_COMPLEX_DOUBLE=OFF` ?

**Comment by cgcgcg** [comment]
@markyoder Could you try if your build goes through with Trilinos develop and complex and/or float disabled? Or do you need all of them?

**Comment by markyoder** [comment]
thanks for your help with this!
I can compile it on the * develop * branch, except...:
1) If I include tests, some of the tests fail to compile
2) If I include muelu, get the errors posted below (and more like them).

So I exclude MueLu and the tests. This compiles, but I still get errors
when I try to compile Deal.II with this build of Trilinos.
```

/scratch/myoder96/Downloads/trilinos/Trilinos/packages/kokkos/core/src/Kokkos_Parallel.hpp:480:13:
error: ‘void Kokkos::parallel_scan(const string&, const ExecutionPolicy&,
const FunctorType&) [with ExecutionPolicy = Kokkos::RangePolicy<int,
Kokkos::OpenMP>; FunctorType = MueLu::CoalesceDropFactory_kokkos<Scalar,
LocalOrdinal, GlobalOrdinal,
Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType>
>::Build(MueLu::CoalesceDropFactory_kokkos<Scalar, LocalOrdinal,
GlobalOrdinal, Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType>
>::Level&) const [with Scalar = std::complex<float>; LocalOrdinal = int;
GlobalOrdinal = long long int; DeviceType = Kokkos::OpenMP; typename
DeviceType::memory_space = Kokkos::HostSpace;
MueLu::CoalesceDropFactory_kokkos<Scalar, LocalOrdinal, GlobalOrdinal,
Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType> >::Level =
MueLu::Level]::<lambda(MueLu::CoalesceDropFactory_kokkos<std::complex<float>,
int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>
>::LO, MueLu::CoalesceDropFactory_kokkos<std::complex<float>, int, long
long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >::LO&,
const bool&)>; std::__cxx11::string = std::__cxx11::basic_string<char>]’,
declared using local type ‘const MueLu::CoalesceDropFactory_kokkos<Scalar,
LocalOrdinal, GlobalOrdinal,
Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType>
>::Build(MueLu::CoalesceDropFactory_kokkos<Scalar, LocalOrdinal,
GlobalOrdinal, Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType>
>::Level&) const [with Scalar = std::complex<float>; LocalOrdinal = int;
GlobalOrdinal = long long int; DeviceType = Kokkos::OpenMP; typename
DeviceType::memory_space = Kokkos::HostSpace;
MueLu::CoalesceDropFactory_kokkos<Scalar, LocalOrdinal, GlobalOrdinal,
Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType> >::Level =
MueLu::Level]::<lambda(MueLu::CoalesceDropFactory_kokkos<std::complex<float>,
int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>
>::LO, MueLu::CoalesceDropFactory_kokkos<std::complex<float>, int, long
long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP> >::LO&,
const bool&)>’, is used but never defined [-fpermissive]

 inline void parallel_scan(const std::string& str, const ExecutionPolicy&
policy,

             ^~~~~~~~~~~~~

In file included from
/scratch/myoder96/Downloads/trilinos/Trilinos/packages/kokkos/core/src/Kokkos_Serial.hpp:56,

                 from
/scratch/myoder96/Downloads/trilinos/Trilinos/packages/kokkos/core/src/Kokkos_Core.hpp:54,

                 from
/scratch/myoder96/Downloads/trilinos/Trilinos/packages/teuchos/kokkoscompat/src/KokkosCompat_ClassicNodeAPI_Wrapper.hpp:6,

                 from
/scratch/myoder96/Downloads/trilinos/Trilinos/packages/tpetra/classic/NodeAPI/Kokkos_DefaultNode.hpp:47,

                 from
/scratch/myoder96/Downloads/trilinos/Trilinos/packages/muelu/src/Headers/MueLu_ConfigDefs.hpp:54,

                 from
/scratch/myoder96/Downloads/trilinos/Trilinos/build_gnu8_openmpi3/packages/muelu/src/Utils/ExplicitInstantiation/MueLu_CoalesceDropFactory_kokkos.cpp:49:

/scratch/myoder96/Downloads/trilinos/Trilinos/packages/kokkos/core/src/Kokkos_Parallel.hpp:225:13:
error: ‘void Kokkos::parallel_for(const string&, const ExecPolicy&, const
FunctorType&) [with ExecPolicy = Kokkos::RangePolicy<int, Kokkos::OpenMP>;
FunctorType = MueLu::CoalesceDropFactory_kokkos<Scalar, LocalOrdinal,
GlobalOrdinal, Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType>
>::Build(MueLu::CoalesceDropFactory_kokkos<Scalar, LocalOrdinal,
GlobalOrdinal, Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType>
>::Level&) const [with Scalar = std::complex<float>; LocalOrdinal = int;
GlobalOrdinal = long long int; DeviceType = Kokkos::OpenMP; typename
DeviceType::memory_space = Kokkos::HostSpace;
MueLu::CoalesceDropFactory_kokkos<Scalar, LocalOrdinal, GlobalOrdinal,
Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType> >::Level =
MueLu::Level]::<lambda(MueLu::CoalesceDropFactory_kokkos<std::complex<float>,
int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>
>::LO)>; std::__cxx11::string = std::__cxx11::basic_string<char>]’,
declared using local type ‘const MueLu::CoalesceDropFactory_kokkos<Scalar,
LocalOrdinal, GlobalOrdinal,
Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType>
>::Build(MueLu::CoalesceDropFactory_kokkos<Scalar, LocalOrdinal,
GlobalOrdinal, Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType>
>::Level&) const [with Scalar = std::complex<float>; LocalOrdinal = int;
GlobalOrdinal = long long int; DeviceType = Kokkos::OpenMP; typename
DeviceType::memory_space = Kokkos::HostSpace;
MueLu::CoalesceDropFactory_kokkos<Scalar, LocalOrdinal, GlobalOrdinal,
Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType> >::Level =
MueLu::Level]::<lambda(MueLu::CoalesceDropFactory_kokkos<std::complex<float>,
int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>
>::LO)>’, is used but never defined [-fpermissive]

 inline void parallel_for(const std::string& str, const ExecPolicy& policy,

             ^~~~~~~~~~~~

/scratch/myoder96/Downloads/trilinos/Trilinos/packages/kokkos/core/src/Kokkos_Parallel.hpp:225:13:
error: ‘void Kokkos::parallel_for(const string&, const ExecPolicy&, const
FunctorType&) [with ExecPolicy = Kokkos::RangePolicy<int, Kokkos::OpenMP>;
FunctorType = MueLu::CoalesceDropFactory_kokkos<Scalar, LocalOrdinal,
GlobalOrdinal, Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType>
>::Build(MueLu::CoalesceDropFactory_kokkos<Scalar, LocalOrdinal,
GlobalOrdinal, Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType>
>::Level&) const [with Scalar = std::complex<float>; LocalOrdinal = int;
GlobalOrdinal = long long int; DeviceType = Kokkos::OpenMP; typename
DeviceType::memory_space = Kokkos::HostSpace;
MueLu::CoalesceDropFactory_kokkos<Scalar, LocalOrdinal, GlobalOrdinal,
Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType> >::Level =
MueLu::Level]::<lambda(MueLu::CoalesceDropFactory_kokkos<std::complex<float>,
int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>
>::LO)>; std::__cxx11::string = std::__cxx11::basic_string<char>]’,
declared using local type ‘const MueLu::CoalesceDropFactory_kokkos<Scalar,
LocalOrdinal, GlobalOrdinal,
Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType>
>::Build(MueLu::CoalesceDropFactory_kokkos<Scalar, LocalOrdinal,
GlobalOrdinal, Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType>
>::Level&) const [with Scalar = std::complex<float>; LocalOrdinal = int;
GlobalOrdinal = long long int; DeviceType = Kokkos::OpenMP; typename
DeviceType::memory_space = Kokkos::HostSpace;
MueLu::CoalesceDropFactory_kokkos<Scalar, LocalOrdinal, GlobalOrdinal,
Kokkos::Compat::KokkosDeviceWrapperNode<DeviceType> >::Level =
MueLu::Level]::<lambda(MueLu::CoalesceDropFactory_kokkos<std::complex<float>,
int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::OpenMP>
>::LO)>’, is used but never defined [-fpermissive]

In file included from
/scratch/myoder96/Downloads/trilinos/Trilinos/packages/kokkos/core/src/Kokkos_Parallel.hpp:243,

                 from
/scratch/myoder96/Downloads/trilinos/Trilinos/packages/kokkos/core/src/Kokkos_Serial.hpp:56,

                 from
/scratch/myoder96/Downloads/trilinos/Trilinos/packages/kokkos/core/src/Kokkos_Core.hpp:54,

                 from
/scratch/myoder96/Downloads/trilinos/Trilinos/packages/teuchos/kokkoscompat/src/KokkosCompat_ClassicNodeAPI_Wrapper.hpp:6,

                 from
/scratch/myoder96/Downloads/trilinos/Trilinos/packages/tpetra/classic/NodeAPI/Kokkos_DefaultNode.hpp:47,

                 from
/scratch/myoder96/Downloads/trilinos/Trilinos/packages/muelu/src/Headers/MueLu_ConfigDefs.hpp:54,

                 from
/scratch/myoder96/Downloads/trilinos/Trilinos/build_gnu8_openmpi3/packages/muelu/src/Utils/ExplicitInstantiation/MueLu_CoalesceDropFactory_kokkos.cpp:49:
```


Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"If you bore me, you lose your soul (to me)..."
~belly

**Comment by cgcgcg** [comment]
We regularly test with `complex<double>`, and I know that `float` worked not that long ago. But I don't believe that I have ever tried `complex<float>`. Is this actually needed?

**Comment by markyoder** [comment]
I don't know if i need complex<float>, but I don't think it is (directly)
causing problems. I think I'd added it when I was getting errors about
unsupported arithmetic operations.

Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"If you bore me, you lose your soul (to me)..."
~belly

**Comment by cgcgcg** [comment]
Could you try disabling it again? From the error messages above, it looks like it always involves `complex<float>` instantiations.

**Comment by markyoder** [comment]
you know... that seems to have worked! As per my notes to myself, :
- enabled MueLu
- Disabled anything I had that explicitly said FLOAT (
- Just excluded -DTrilinos_ENABLE_COMPLEX= , so left it to whatever its
default behavior is.
- Specifically, this was a gnu/8.3.0, openmpi/3.1.4 build.

I'm happy to send you all the things, but 1) my compile script is a bit of
a mess -- as per multiple passes and guessing of parameter syntax to get it
to compile. I can clean it up a bit, 2) the full output file is 20+MB, but
maybe you want the full configure portion of it? It might be important to
both the parameter inputs and then enabled packages outputs, since I thing
there are a few wires crossed there (hence, getting header/code body
mismatching errors).

I'll also go ahead and try it with the tests on and then see if I get lucky
with the Deal.II build (where there appears to be a Trilinos related build
fail).

Thanks for your help! Let me know if I can help more with the
troubleshooting; I'd love to see a shiny, new release come out before too
long.

mark




Mark Yoder, PhD
805 451 8750
*www.linkedin.com/in/Mark-R-Yoder-PhD
<http://www.linkedin.com/in/Mark-R-Yoder-PhD>*

"If you bore me, you lose your soul (to me)..."
~belly

**Comment by cgcgcg** [comment]
@markyoder Great, thanks for trying that out! Please let us know if it really and truly fixed it, then we can close this issue.
