### ISSUE TITLE
Phalanx: move createDynRankView from Panzer into Sacado

### ISSUE THREAD

**Issue by rppawlo** [trilinos/Trilinos#366]
This function was implemented in Panzer but Albany would like to use as well. Since they depend on phalanx but not panzer, it makes more sense to move it here.

**Comment by rppawlo** [comment]
@trilinos/panzer @mperego

**Comment by etphipp** [comment]
Should we put it in Sacado instead?  It could be written to not reference PHX::Device, something like this:

```
  template<typename InputArray,typename ... DimensionPack>
  Kokkos::DynRankView<typename InputArray::value_type,PHX::Device>
  createDynRankView(const InputArray& a, const std::string& name, const DimensionPack... dims)
  {
    using return_type = Kokkos::DynRankView<typename InputArray::value_type, typename inputArray::array_layout, typename inputArray::device_type, typename InputArray::memory_traits>;
    return Kokkos::ViewFactory<InputArray>::template create_view<return_type>(a,name,dims...);
  }
```

**Comment by etphipp** [comment]
Whoops, that should have been:

```
  template<typename InputArray,typename ... DimensionPack>
  Kokkos::DynRankView<typename InputArray::value_type, typename inputArray::array_layout, typename inputArray::device_type, typename InputArray::memory_traits>
  createDynRankView(const InputArray& a, const std::string& name, const DimensionPack... dims)
  {
    using return_type = Kokkos::DynRankView<typename InputArray::value_type, typename inputArray::array_layout, typename inputArray::device_type, typename InputArray::memory_traits>;
    return Kokkos::ViewFactory<InputArray>::template create_view<return_type>(a,name,dims...);
  }
```

**Comment by rppawlo** [comment]
I do think sacado would be a better place for this. And changing the template parameters may help with an additional issue I had yet to fix (item 2 below).
1. From a transition standpoint it should be an easy sed script over all files, but multiple applications will need to be changed. Maybe we copy to sacado in short term and remove from panzer after all applications are fixed. Currently any use of this function includes the file 
#include "Panzer_ViewFactory.hpp"
and then invokes with:
a = panzer::createDynRankView(other_view_with_fad_dim,"name",dimension_pack);
I'd like to make sure we keep these simple semantics.
2. The issue I have right now (and have not addressed yet) is that the function compiles when the first object passed in is an MDField as well as Kokkos Views. And if an MDField is accidentally passed in for the first argument, the sacado dimension is not set correctly and you get a runtime seg fault. So in a refactor I would like to make sure the function generates a compile time failure if an MDField is the first argument.  

@etphipp how do you want to proceed? Do you want to add it to sacado or should I? There is also a corresponding unit test in panzer disc-fe that would be a good base for sacado testing.

**Comment by etphipp** [comment]
I'll put it in Sacado.  And for the first step you can just have the panzer one call the sacado one.  Where is the test in panzer?  We can prevent it compiling when you accidentally pass in an MDField by doing something by restricting the InputArray to be a DynRankView.

**Comment by rppawlo** [comment]
Trilinos/packages/panzer/disc-fe/test/core_tests/view_factory.cpp

Great! Thanks Eric! 

One thing I didn't add to testing for was if the data_type of the incoming array was const: 

DynRankView<const double> a(...) ;

Apparently we didn't need that but might want support for mixing const/non-const as well (e.g. create a non-const DynRankView from a const input).

**Comment by etphipp** [comment]
Here's my implementation:

```
template< class > struct is_dyn_rank_view : public std::false_type {};

template< class D, class ... P >
struct is_dyn_rank_view< DynRankView<D,P...> > : public std::true_type {};


//! Wrapper to simplify use of Sacado ViewFactory -- non-const scalar type
template <typename InputViewType, typename CtorProp, typename ... Dims>
typename std::enable_if<
  is_view<InputViewType>::value || is_dyn_rank_view<InputViewType>::value,
  Kokkos::DynRankView<typename InputViewType::non_const_value_type,
                      typename InputViewType::array_layout,
                      typename InputViewType::device_type,
                      typename InputViewType::memory_traits> >::type
createDynRankView(const InputViewType& a,
                  const CtorProp& prop,
                  const Dims... dims)
{
  using view_factory = Kokkos::ViewFactory<InputViewType>;
  using return_type =
    Kokkos::DynRankView<typename InputViewType::non_const_value_type,
                        typename InputViewType::array_layout,
                        typename InputViewType::device_type,
                        typename InputViewType::memory_traits>;
  return view_factory::template create_view<return_type>(a,prop,dims...);
}
```
It's in the Kokkos namespace, and I'm not sure if that's the best choice (I've been randomly choosing to put things like this in the Sacado and Kokkos namespaces, with no obvious logic).

**Comment by etphipp** [comment]
I pushed the implementation above into Sacado.  I also copied the Panzer test.

**Comment by rppawlo** [comment]
Thanks Eric! I will switch over panzer and all the applications tomorrow. It should really be just a simple sed script. 

Is there a reason that the new kokkos files you are creating in sacado still have the Exp in the file name (KokkosExp_<>.hpp)? The experimental view is now the default so I would think that we can get rid of the Exp tag.

**Comment by rppawlo** [comment]
Panzer and Drekar have been converted over to use the sacado version rather than panzer version. Putting this ticket into review. If the nightly tests pass for the next few days will move to done.

**Comment by etphipp** [comment]
I have Exp in the name because the code is dependent on the experimental view.  I did that to be consistent with other files dependent on the experimental view, to make it easier in the future to know what we need to change when we finally delete the old view implementation.  However I can see that this would require changing a bunch of files once we change the name.  So I am guessing it would be better if I didn't put Exp in the filename?

**Comment by etphipp** [comment]
I just renamed the file.  I also left a file called KokkosExp_ViewFactory.hpp there which just includes Kokkos_ViewFactory.hpp.

**Comment by rppawlo** [comment]
Thanks! I just updated panzer, Drekar, etc... to use the new filename. You could probably safely delete the old file now unless Albany is still using it.

**Comment by etphipp** [comment]
I just pushed a few small tweaks.  I added another version of the function, createDynRankViewWithType<ReturnType> where you specify the type of view you want created.  This is to allow for cases when the default isn't what you want (I tried to modify the original version with this template parameter, but set a default for it, but I couldn't get it to work, hence the new function).  I also created a similar createViewWithType for creating a Kokkos::View instead of DynRankView (a createView() doesn't make sense to me because you need to specify the rank, and choosing a default rank would be problematic I think).  Finally I removed the memory_traits from the return type in createDynRankView, since the input view might be unmanaged and you don't want to propagate that to the return type.

**Comment by agsalin** [comment]
Thanks. You can remove the KokkosExp_ViewFactory.hpp as far as Albany is concerned.

**Comment by etphipp** [comment]
I removed KokkosExp_ViewFactory.hpp
