### ISSUE TITLE
PyTeuchos:  undefined identifiers

### ISSUE THREAD

**Issue by VictorEijkhout** [trilinos/Trilinos#9013]
```
/tmp/trilinos-build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp(33622): error: identifier "ParameterListModifier" is undefined
    Teuchos::RCP< ParameterListModifier const > const &arg2_defvalue = null ;
                  ^

/tmp/trilinos-build/packages/PyTrilinos/src/TeuchosPYTHON_wrap.cpp(33622): error: identifier "null" is undefined
    Teuchos::RCP< ParameterListModifier const > const &arg2_defvalue = null ;
                                                                       ^
```

## Bug Report
@trilinos/pytrilinos 

### Description
complation fails

configuration/build log attached. 
[trilinos_log.zip](https://github.com/trilinos/Trilinos/files/6319179/trilinos_log.zip)

**Comment by VictorEijkhout** [comment]
Can I get help with this? Are python bindings still supported? I have users for this....

**Comment by pyt-viper** [comment]
OK.  I will try to look at this today.

**Comment by VictorEijkhout** [comment]
How is this going?

**Comment by pyt-viper** [comment]
I'm still trying to recreate the error.  I have produced *an* error, but not the one you are reporting ... although it could be the same or related.  Unfortunately, this is a very busy time for me.

**Comment by VictorEijkhout** [comment]
How is this going?

**Comment by pyt-viper** [comment]
I was able to recreate the error using a reduced build configuration.  So now I can try to figure out why it is happening...

**Comment by pyt-viper** [comment]
@VictorEijkhout I figured out the problem and implemented a fix.  Now I have to figure out how and where to push it back to the repository.  How do you get the Trilinos source?  Do you `git checkout` the `trilinos-release-12-18-branch` branch?

**Comment by VictorEijkhout** [comment]
I downloaded the 13 release.

If you can make a branch that is newer than that I can check that out.

Victor.

On , 2021May4, at 18:37, Pyt Viper ***@***.******@***.***>> wrote:



@VictorEijkhout<https://github.com/VictorEijkhout> I figured out the problem and implemented a fix. Now I have to figure out how and where to push it back to the repository. How do you get the Trilinos source? Do you git checkout the trilinos-release-12-18-branch branch?

**Comment by pyt-viper** [comment]
@jwillenbring It's been a while since I have pushed to the Trilinos GitHub repository.  It looks like I will need to push a fix to the `trilinos-release-12-18-branch` branch (if that is allowed) and then cherry pick it to the `develop` branch.  is there a process for the first step?  Thx

**Comment by pyt-viper** [comment]
@jwillenbring OK, I have a local branch called `trilinos-release-13-0-pyteuchos-fix`, which is branched off my `trilinos-release-13-0-branch` that contains the PyTrilinos fix to this build error.  I would like to push it to the `trilinos` remote.  Is that allowed?

**Comment by jwillenbring** [comment]
@pyt-viper The PR process for release branches is the same as for develop. You can just issue a PR and the PR testing should grab it. If it doesn't, let me know. The release PR testing only runs about once a day if I remember right. It is rarely used. Then you can just cherry-pick your change onto the develop branch too and issue a PR for that.

**Comment by pyt-viper** [comment]
@jwillenbring OK, sounds good.

**Comment by pyt-viper** [comment]
@VictorEijkhout The fix has been merged into `Trilinos-release-13-0-branch`.

**Comment by VictorEijkhout** [comment]
***@***.***BLDCHROOT:SOURCES # git clone ***@***.***:trilinos/Trilinos.git trilinos-git
Cloning into 'trilinos-git'...
The authenticity of host 'github.com (140.82.112.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
RSA key fingerprint is MD5:16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.112.3' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by VictorEijkhout** [comment]
I've downloaded the release, but why can't I git clone?

**Comment by VictorEijkhout** [comment]
Python still doesn't work:

```
[100%] Generating Teuchos.RCP.i
cd /tmp/trilinos-build/packages/PyTrilinos/src && /usr/bin/python /tmp/trilinos-build/packages/PyTrilinos/src/gen_teuchos_rcp.py > /tmp/trilinos-build/packages/PyTrilinos/src/Teuchos.RCP.i
Dependee "/tmp/trilinos-build/packages/panzer/mini-em/example/BlockPrec/CMakeFiles/PanzerMiniEM_BlockPrec.dir/DependInfo.cmake" is newer than depender "/tmp/trilinos-build/packages/panzer/mini-em/exampl\
e/BlockPrec/CMakeFiles/PanzerMiniEM_BlockPrec.dir/depend.internal".
Dependee "/tmp/trilinos-build/packages/panzer/mini-em/example/BlockPrec/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/tmp/trilinos-build/packages/panzer/mini-em/example/BlockPrec/\
CMakeFiles/PanzerMiniEM_BlockPrec.dir/depend.internal".
Traceback (most recent call last):
  File "/tmp/trilinos-build/packages/PyTrilinos/src/gen_teuchos_rcp.py", line 659, in <module>
    main()
  File "/tmp/trilinos-build/packages/PyTrilinos/src/gen_teuchos_rcp.py", line 557, in main
    print("#define MPI_VERSION %s" % get_mpi_version())
  File "/tmp/trilinos-build/packages/PyTrilinos/src/gen_teuchos_rcp.py", line 58, in get_mpi_version
    for line in open(header, 'r').readlines():
IOError: [Errno 2] No such file or directory: '/include/mpi.h'
```
[trilinos13.zip](https://github.com/trilinos/Trilinos/files/6517434/trilinos13.zip)

**Comment by pyt-viper** [comment]
@VictorEijkhout PyTrilinos tried to find the location of the mpi.h header and failed.  Do you know where it is?  Or why a standard way to look for it might fail?

**Comment by VictorEijkhout** [comment]
On , 2021May21, at 11:39, Pyt Viper ***@***.******@***.***>> wrote:



@VictorEijkhout<https://github.com/VictorEijkhout> PyTrilinos tried to find the location of the mpi.h header and failed.

I got that.

Do you know where it is?

Yes, it’s the normal location for intel compilers. I can specify that location if there is a cmake option for it.


Or why a standard way to look for it might fail?


No idea.

Victor.

**Comment by jhux2** [comment]
> Yes, it’s the normal location for intel compilers. I can specify that location if there is a cmake option for it.

There is.  See https://github.com/trilinos/Trilinos/#readme, in particular "Quick configure, build and install hints for Trilinos".

**Comment by VictorEijkhout** [comment]
Seems like `TPL_MPI_DIR` is now `MPI_BASE_DIR`?
Also: specifying both MPI base dir & include dir seems to confuse your cmake.
Anyway, it now works. Thanks.

**Comment by jhux2** [comment]
Thanks, @pyt-viper!
